"""Deterministic tools for the PGSI triage agent."""

import json
import re
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field

EXPECTED_ITEM_IDS = [f"q{i}" for i in range(1, 10)]
EXPECTED_SCALE_KEYS = ["0", "1", "2", "3"]

REFERRALS: tuple[str, ...] = (
    "Plataforma centralizada de autoexclusão de apostas: gov.br",
    "CVV: ligue 188, gratuito, 24 horas por dia, todos os dias",
    "Rede CAPS/SUS: procure a unidade de saúde mais próxima",
)
DISCLAIMER = (
    "Este resultado é uma triagem educacional e não constitui diagnóstico "
    "nem substitui avaliação profissional."
)


class PGSIDataError(Exception):
    """Raised when the PGSI data file is missing, malformed or incomplete."""


class Question(BaseModel):
    id: str
    text: str


def _read_pgsi_data(path: str) -> dict:
    """Read and parse the PGSI data file; raises PGSIDataError on I/O or JSON errors."""
    file = Path(path)
    if not file.is_file():
        raise PGSIDataError(f"PGSI data file not found: {path}")
    try:
        raw = json.loads(file.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise PGSIDataError(f"PGSI data file is not valid JSON: {exc}") from exc
    return raw


def load_pgsi_questions(path: str = "data/pgsi.json") -> list[Question]:
    """Load and validate the PGSI items: exactly 9, ids q1..q9 in order, non-empty text.

    Raises PGSIDataError with a clear message when the file is malformed.
    """
    raw = _read_pgsi_data(path)
    items = raw.get("items") if isinstance(raw, dict) else None
    if not isinstance(items, list):
        raise PGSIDataError("PGSI data must contain an 'items' list")
    if len(items) != 9:
        raise PGSIDataError(f"PGSI requires exactly 9 items, found {len(items)}")
    questions: list[Question] = []
    for expected_id, item in zip(EXPECTED_ITEM_IDS, items):
        item_id = item.get("id") if isinstance(item, dict) else None
        text = item.get("text") if isinstance(item, dict) else None
        if item_id != expected_id:
            raise PGSIDataError(f"expected item '{expected_id}', found '{item_id}'")
        if not isinstance(text, str) or not text.strip():
            raise PGSIDataError(f"item '{expected_id}' has empty or missing text")
        questions.append(Question(id=item_id, text=text))
    return questions


def load_pgsi_scale(path: str = "data/pgsi.json") -> dict[str, str]:
    """Load and validate the response scale: keys exactly "0".."3", non-empty labels.

    Raises PGSIDataError with a clear message when the file is malformed.
    """
    raw = _read_pgsi_data(path)
    scale = raw.get("scale") if isinstance(raw, dict) else None
    if not isinstance(scale, dict):
        raise PGSIDataError("PGSI data must contain a 'scale' dict")
    if sorted(scale) != EXPECTED_SCALE_KEYS:
        raise PGSIDataError(f"PGSI scale must have keys 0..3, found {sorted(scale)}")
    for key in EXPECTED_SCALE_KEYS:
        label = scale[key]
        if not isinstance(label, str) or not label.strip():
            raise PGSIDataError(f"scale value for '{key}' has empty or missing label")
    return {key: scale[key] for key in EXPECTED_SCALE_KEYS}


class ScoreResult(BaseModel):
    score: int  # 0..27
    answers: dict[str, int]


def compute_pgsi_score(answers: dict[str, int]) -> ScoreResult:
    """Controlled pure scoring: requires exactly q1..q9 with int values 0..3.

    Raises ValueError on any violation; never returns a partial score. No I/O.
    """
    missing = [item_id for item_id in EXPECTED_ITEM_IDS if item_id not in answers]
    if missing:
        raise ValueError(f"missing answers for: {', '.join(missing)}")
    extra = sorted(key for key in answers if key not in EXPECTED_ITEM_IDS)
    if extra:
        raise ValueError(f"unexpected answer keys: {', '.join(extra)}")
    for item_id in EXPECTED_ITEM_IDS:
        value = answers[item_id]
        if type(value) is not int or not 0 <= value <= 3:
            raise ValueError(
                f"answer '{item_id}' must be an int between 0 and 3, got {value!r}"
            )
    return ScoreResult(
        score=sum(answers[item_id] for item_id in EXPECTED_ITEM_IDS),
        answers=dict(answers),
    )


class TriageOutcome(BaseModel):
    thread_id: str
    timestamp: str  # ISO-8601 with seconds, generated by the calling node
    score: int
    severity_band: Literal["sem_risco", "baixo", "moderado", "alto"]
    answers: dict[str, int]
    referrals: list[str] = Field(default_factory=lambda: list(REFERRALS))
    disclaimer: str = DISCLAIMER


def _sanitize_thread_id(thread_id: str) -> str:
    """Defend against path traversal: keep only safe chars, cap length, never empty."""
    cleaned = re.sub(r"[^A-Za-z0-9_-]", "", thread_id)[:32]
    return cleaned or "sem-id"


def write_triage_report(result: TriageOutcome, out_dir: str = "reports") -> str:
    """Write .md and .json report files with a timestamped name; refuses to overwrite.

    Returns the path to the .md file. D-08: single source for referrals/disclaimer.
    """
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)

    thread = _sanitize_thread_id(result.thread_id)
    stamp = result.timestamp.replace("-", "").replace(":", "")
    stem = f"triagem-{thread}-{stamp}"
    md_path = directory / f"{stem}.md"
    json_path = directory / f"{stem}.json"

    if md_path.exists() or json_path.exists():
        raise FileExistsError(f"report already exists: {md_path}")

    answer_lines = "\n".join(
        f"- {item_id}: {result.answers[item_id]}"
        for item_id in EXPECTED_ITEM_IDS
        if item_id in result.answers
    )
    referral_lines = "\n".join(f"- {referral}" for referral in result.referrals)
    markdown = (
        "# Relatório de triagem PGSI\n\n"
        f"Thread: {result.thread_id}\n\n"
        f"Data e hora: {result.timestamp}\n\n"
        f"Pontuação: {result.score} de 27\n\n"
        f"Faixa: {result.severity_band}\n\n"
        "## Respostas\n\n"
        f"{answer_lines}\n\n"
        "## Encaminhamentos\n\n"
        f"{referral_lines}\n\n"
        f"{result.disclaimer}\n"
    )
    md_path.write_text(markdown, encoding="utf-8")
    json_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    return str(md_path)
